name: PR Quality Checks
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    test:
        name: Start test setup
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'

            - uses: actions/cache@v3
              id: cache
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.*') }}
                restore-keys: | 
                  ${{ runner.os }}-pip-

            - name: Install Python dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Test with pytest
              run: |
                pytest tests/ 

            - name: Lint with Ruff
              run: |
                ruff --output-format=github .
              continue-on-error: true